param(
    [string]$Year = $env:SUPEX_SKETCHUP_YEAR,
    [string]$PluginsDir = $env:SUPEX_SKETCHUP_PLUGINS_DIR,
    [switch]$Uninstall
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$SupexRoot = Split-Path -Parent $ScriptDir
$Injector = Join-Path $SupexRoot "runtime\src\injector.rb"

function ConvertTo-RubySingleQuotedString {
    param([Parameter(Mandatory = $true)][string]$Value)

    return $Value.Replace("\", "/").Replace("'", "\'")
}

function Get-CandidatePluginsDirs {
    $Years = if ($Year) { @($Year) } else { @("2026", "2025", "2024") }
    foreach ($CandidateYear in $Years) {
        if ($env:APPDATA) {
            Join-Path $env:APPDATA "SketchUp\SketchUp $CandidateYear\SketchUp\Plugins"
        }
    }
}

function Resolve-PluginsDir {
    if ($PluginsDir) {
        return $PluginsDir
    }

    $Candidates = @(Get-CandidatePluginsDirs)
    foreach ($Candidate in $Candidates) {
        $Parent = Split-Path -Parent $Candidate
        if ((Test-Path $Candidate -PathType Container) -or (Test-Path $Parent -PathType Container)) {
            return $Candidate
        }
    }

    if ($Year -and $Candidates.Count -gt 0) {
        return $Candidates[0]
    }

    throw "Could not find a SketchUp profile under APPDATA. Launch SketchUp once, pass -Year, or set SUPEX_SKETCHUP_PLUGINS_DIR."
}

if (-not (Test-Path $Injector -PathType Leaf)) {
    throw "Injector script not found: $Injector"
}

$ResolvedPluginsDir = Resolve-PluginsDir
$LoaderFile = Join-Path $ResolvedPluginsDir "supex_dev_loader.rb"

if ($Uninstall) {
    if (Test-Path $LoaderFile -PathType Leaf) {
        Remove-Item $LoaderFile -Force
        Write-Host "Removed Supex dev loader: $LoaderFile"
    } else {
        Write-Host "Supex dev loader was not installed: $LoaderFile"
    }
    exit 0
}

New-Item -ItemType Directory -Force -Path $ResolvedPluginsDir | Out-Null

$InjectorRuby = ConvertTo-RubySingleQuotedString -Value (Resolve-Path $Injector).Path
$SupexRootRuby = ConvertTo-RubySingleQuotedString -Value (Resolve-Path $SupexRoot).Path

$Loader = @"
# frozen_string_literal: true

# Generated by scripts/install-dev-extension.ps1.
# Safe to delete; rerun the installer to recreate it.
module SupexDevLoader
  INJECTOR = '$InjectorRuby'
  REPO_ROOT = '$SupexRootRuby'

  def self.load_runtime
    ENV['SUPEX_WORKSPACE'] ||= REPO_ROOT
    ENV['SUPEX_LOG_DIR'] ||= File.join(ENV['SUPEX_WORKSPACE'], '.tmp', 'logs')
    ENV['SUPEX_DEV_LOADER'] = '1'

    unless File.exist?(INJECTOR)
      puts "Supex dev loader: injector not found: #{INJECTOR}"
      return
    end

    load INJECTOR
  rescue StandardError => e
    puts "Supex dev loader failed: #{e.class}: #{e.message}"
    puts e.backtrace.join("\n") if e.backtrace
    begin
      SKETCHUP_CONSOLE.show if defined?(SKETCHUP_CONSOLE)
    rescue StandardError
      nil
    end
  end
end

SupexDevLoader.load_runtime
"@

$Utf8NoBom = New-Object System.Text.UTF8Encoding -ArgumentList $false
[System.IO.File]::WriteAllText($LoaderFile, $Loader, $Utf8NoBom)

Write-Host "Installed Supex dev loader: $LoaderFile"
Write-Host "Runtime injector: $Injector"
Write-Host "Restart SketchUp to load the development runtime."
