#!/usr/bin/env bash
# Install a SketchUp Plugins loader that points at this checkout's runtime sources.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

source "$SCRIPT_DIR/helpers/common.sh"

SKETCHUP_YEAR="${SUPEX_SKETCHUP_YEAR:-}"
PLUGINS_DIR="${SUPEX_SKETCHUP_PLUGINS_DIR:-}"
UNINSTALL=0

usage() {
    cat <<'USAGE'
Usage: install-dev-extension.sh [--year YEAR] [--plugins-dir PATH] [--uninstall]
  --year YEAR       SketchUp version year to target (default: first installed 2026, 2025, 2024)
  --plugins-dir     Explicit SketchUp Plugins directory
  --uninstall       Remove the Supex dev loader instead of installing it
USAGE
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --year)
            if [[ -z "${2:-}" ]]; then
                log_error "--year requires a value"
                exit 1
            fi
            SKETCHUP_YEAR="$2"
            shift 2
            ;;
        --plugins-dir)
            if [[ -z "${2:-}" ]]; then
                log_error "--plugins-dir requires a path"
                exit 1
            fi
            PLUGINS_DIR="$2"
            shift 2
            ;;
        --uninstall)
            UNINSTALL=1
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        --*)
            log_error "Unknown option: $1"
            usage
            exit 1
            ;;
        *)
            log_error "Unexpected argument: $1"
            usage
            exit 1
            ;;
    esac
done

ruby_single_quote() {
    local value="$1"
    value="${value//\\/\/}"
    value="${value//\'/\\\'}"
    printf "%s" "$value"
}

candidate_plugins_dirs() {
    local years=()
    if [[ -n "$SKETCHUP_YEAR" ]]; then
        years=("$SKETCHUP_YEAR")
    else
        years=(2026 2025 2024)
    fi

    local year
    for year in "${years[@]}"; do
        printf "%s\n" "$HOME/Library/Application Support/SketchUp ${year}/SketchUp/Plugins"
    done
}

resolve_plugins_dir() {
    if [[ -n "$PLUGINS_DIR" ]]; then
        printf "%s\n" "$PLUGINS_DIR"
        return 0
    fi

    local first_candidate=""
    local candidate parent
    while IFS= read -r candidate; do
        [[ -z "$first_candidate" ]] && first_candidate="$candidate"
        parent="$(dirname "$candidate")"
        if [[ -d "$candidate" || -d "$parent" ]]; then
            printf "%s\n" "$candidate"
            return 0
        fi
    done < <(candidate_plugins_dirs)

    if [[ -n "$SKETCHUP_YEAR" && -n "$first_candidate" ]]; then
        printf "%s\n" "$first_candidate"
        return 0
    fi

    log_error "Could not find a SketchUp profile under ~/Library/Application Support."
    log_error "Launch SketchUp once, pass --year, or set SUPEX_SKETCHUP_PLUGINS_DIR."
    exit 1
}

INJECTOR="$PROJECT_ROOT/runtime/src/injector.rb"
if [[ ! -f "$INJECTOR" ]]; then
    log_error "Injector script not found: $INJECTOR"
    exit 1
fi

PLUGINS_DIR="$(resolve_plugins_dir)"
LOADER_FILE="$PLUGINS_DIR/supex_dev_loader.rb"

if (( UNINSTALL )); then
    if [[ -f "$LOADER_FILE" ]]; then
        rm "$LOADER_FILE"
        log_success "Removed Supex dev loader: $LOADER_FILE"
    else
        log_info "Supex dev loader was not installed: $LOADER_FILE"
    fi
    exit 0
fi

mkdir -p "$PLUGINS_DIR"

INJECTOR_RUBY="$(ruby_single_quote "$INJECTOR")"
PROJECT_ROOT_RUBY="$(ruby_single_quote "$PROJECT_ROOT")"

cat > "$LOADER_FILE" <<RUBY
# frozen_string_literal: true

# Generated by scripts/install-dev-extension.sh.
# Safe to delete; rerun the installer to recreate it.
module SupexDevLoader
  INJECTOR = '$INJECTOR_RUBY'
  REPO_ROOT = '$PROJECT_ROOT_RUBY'

  def self.load_runtime
    ENV['SUPEX_WORKSPACE'] ||= REPO_ROOT
    ENV['SUPEX_LOG_DIR'] ||= File.join(ENV['SUPEX_WORKSPACE'], '.tmp', 'logs')
    ENV['SUPEX_DEV_LOADER'] = '1'

    unless File.exist?(INJECTOR)
      puts "Supex dev loader: injector not found: #{INJECTOR}"
      return
    end

    load INJECTOR
  rescue StandardError => e
    puts "Supex dev loader failed: #{e.class}: #{e.message}"
    puts e.backtrace.join("\n") if e.backtrace
    begin
      SKETCHUP_CONSOLE.show if defined?(SKETCHUP_CONSOLE)
    rescue StandardError
      nil
    end
  end
end

SupexDevLoader.load_runtime
RUBY

log_success "Installed Supex dev loader: $LOADER_FILE"
log_info "Runtime injector: $INJECTOR"
log_info "Restart SketchUp to load the development runtime."
